apiVersion: apps/v1
kind: Deployment
metadata:
  name: hireme-k8s
spec:
  selector:
    matchLabels:
      app: hireme-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: hireme-k8s
    spec:
      containers:
        - name: hireme-k8s
          image: archie789docker/hireme
          ports:
            - containerPort: 8080