name: Deploy to docker & GKE with Helm

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    if: "contains(github.event.head_commit.message, 'CI push')"
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

#      - name: Build and Push Docker Images
#        run: |
#          TAG=main-${{ github.sha }}
#          docker build -t archie789docker/api:$TAG -f packages/api/Dockerfile .
#          docker push archie789docker/api:$TAG
#          docker build -t archie789docker/frontend:$TAG -f packages/frontend/Dockerfile .
#          docker push archie789docker/frontend:$TAG

      - name: Install Helm
        run: |
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          project_id: 'black-skyline-448810-r4'
          workload_identity_provider: 'projects/983170717422/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: 'github-action@black-skyline-448810-r4.iam.gserviceaccount.com'


      -   name: Configure Docker
          run: gcloud auth configure-docker --quiet

      - name: Configure GKE Cluster
        run: gcloud container clusters get-credentials gke_black-skyline-448810-r4_europe-west1_autopilot-cluster-1 --zone europe-west1

      - name: Deploy API with Helm
        run: |
          helm upgrade --install api ./charts/api \
            --set image.repository=archie789docker/api \
            --set image.tag=main-${{ github.sha }}

#      - name: Deploy Frontend with Helm
#       run: |
#          helm upgrade --install frontend ./charts/frontend \
#            --set image.repository=archie789docker/frontend \
#            --set image.tag=main-${{ github.sha }}